### ISSUE TITLE
KcBERT Train Corpus

### ISSUE THREAD

**Issue by Beomi** [songys/AwesomeKorean_Data#5]
안녕하세요,
혹시 아래와 같은 단순 거대 말뭉치는 어느 항목에 포함하는 것이 좋을까요? :) 
https://www.kaggle.com/junbumlee/kcbert-pretraining-corpus-korean-news-comments

**Comment by songys** [comment]
데이터 링크 감사합니다. 일단 8번 기타에 포함시켰는데 나중에 한 번에 정리하도록 같습니다~
